Update Ansible

diff --git a/Ansible b/Ansible
--- a/Ansible
+++ b/Ansible
@@ -1,254 +1,41 @@
-hsuma@plnx-admin:~/haj/ansible-setup-hosts$ ansible all -i inventory -m ping -u deploy -b
-/usr/lib/python3/dist-packages/paramiko/pkey.py:82: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
-  "cipher": algorithms.TripleDES,
-/usr/lib/python3/dist-packages/paramiko/transport.py:237: CryptographyDeprecationWarning: Blowfish has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.Blowfish and will be removed from this module in 45.0.0.
-  "class": algorithms.Blowfish,
-/usr/lib/python3/dist-packages/paramiko/transport.py:261: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
-  "class": algorithms.TripleDES,
-10.168.0.58 | UNREACHABLE! => {
-    "changed": false,
-    "msg": "Failed to create temporary directory. In some cases, you may have been able to authenticate and did not have permissions on the target directory. Consider changing the remote tmp path in ansible.cfg to a path rooted in \"/tmp\", for more error information use -vvv. Failed command was: ( umask 77 && mkdir -p \"` echo /opt/home/deploy/.ansible/tmp `\"&& mkdir \"` echo /opt/home/deploy/.ansible/tmp/ansible-tmp-1740151748.7210371-417994-227885817154154 `\" && echo ansible-tmp-1740151748.7210371-417994-227885817154154=\"` echo /opt/home/deploy/.ansible/tmp/ansible-tmp-1740151748.7210371-417994-227885817154154 `\" ), exited with result 1",
-    "unreachable": true
+#!/bin/bash
+
+# Define variables
+TARGET_FILE="/etc/sssd/sssd.conf"
+NEW_LINE="ipa_server = _srv_, pln-petipareplica.ipa.calix.local, cpeg-ipareplica.ipa.calix.local"
+
+# Ensure script runs as root
+if [[ $EUID -ne 0 ]]; then
+    echo "This script must be run as root or with sudo." >&2
+    exit 1
+fi
+
+# Function to check if ipa_server line needs updating
+update_sssd_conf() {
+    if grep -q '^ipa_server =' "$TARGET_FILE"; then
+        sed -i "s|^ipa_server =.*|$NEW_LINE|" "$TARGET_FILE"
+        echo "Updated ipa_server entry in $TARGET_FILE"
+        return 0
+    else
+        echo "$NEW_LINE" >> "$TARGET_FILE"
+        echo "Added ipa_server entry to $TARGET_FILE"
+        return 0
+    fi
 }
-hsuma@plnx-admin:~/haj/ansible-setup-hosts$ ansible all -i inventory -m ping -u depl
 
-
-hsuma@plnx-admin:~/haj/ansible-setup-hosts$ ansible all -i inventory -m ping -u deploy -b
-/usr/lib/python3/dist-packages/paramiko/pkey.py:82: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
-  "cipher": algorithms.TripleDES,
-/usr/lib/python3/dist-packages/paramiko/transport.py:237: CryptographyDeprecationWarning: Blowfish has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.Blowfish and will be removed from this module in 45.0.0.
-  "class": algorithms.Blowfish,
-/usr/lib/python3/dist-packages/paramiko/transport.py:261: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
-  "class": algorithms.TripleDES,
-[WARNING]: Unhandled error in Python interpreter discovery for host 10.168.0.58: Expecting value: line 1 column 1 (char 0)
-10.168.0.58 | FAILED! => {
-    "msg": "Missing sudo password"
+# Function to restart SSSD
+restart_sssd() {
+    systemctl restart sssd
+    if [[ $? -eq 0 ]]; then
+        echo "SSSD restarted successfully."
+    else
+        echo "Failed to restart SSSD." >&2
+        exit 1
+    fi
 }
-hsuma@plnx-admin:~/haj/ansible-setup-hosts$ 
 
+# Execute functions
+update_sssd_conf && restart_sssd
 
-hsuma@plnx-admin:~/haj/ansible-setup-hosts$ ansible all -i inventory -m ping -u deploy -b
-/usr/lib/python3/dist-packages/paramiko/pkey.py:82: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
-  "cipher": algorithms.TripleDES,
-/usr/lib/python3/dist-packages/paramiko/transport.py:237: CryptographyDeprecationWarning: Blowfish has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.Blowfish and will be removed from this module in 45.0.0.
-  "class": algorithms.Blowfish,
-/usr/lib/python3/dist-packages/paramiko/transport.py:261: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
-  "class": algorithms.TripleDES,
-[WARNING]: Unhandled error in Python interpreter discovery for host 10.168.0.58: Expecting value: line 1 column 1 (char 0)
-An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SyntaxError: future feature annotations is not defined
-[WARNING]: Platform linux on host 10.168.0.58 is using the discovered Python interpreter at /usr/bin/python3, but future installation of another Python
-interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-core/2.17/reference_appendices/interpreter_discovery.html for
-more information.
-10.168.0.58 | FAILED! => {
-    "ansible_facts": {
-        "discovered_interpreter_python": "/usr/bin/python3"
-    },
-    "changed": false,
-    "module_stderr": "Shared connection to 10.168.0.58 closed.\r\n",
-    "module_stdout": "Traceback (most recent call last):\r\n  File \"/opt/home/deploy/.ansible/tmp/ansible-tmp-1740152345.0802152-418170-277659243960983/AnsiballZ_ping.py\", line 107, in <module>\r\n    _ansiballz_main()\r\n  File \"/opt/home/deploy/.ansible/tmp/ansible-tmp-1740152345.0802152-418170-277659243960983/AnsiballZ_ping.py\", line 99, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/opt/home/deploy/.ansible/tmp/ansible-tmp-1740152345.0802152-418170-277659243960983/AnsiballZ_ping.py\", line 44, in invoke_module\r\n    from ansible.module_utils import basic\r\n  File \"<frozen importlib._bootstrap>\", line 971, in _find_and_load\r\n  File \"<frozen importlib._bootstrap>\", line 951, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 894, in _find_spec\r\n  File \"<frozen importlib._bootstrap_external>\", line 1157, in find_spec\r\n  File \"<frozen importlib._bootstrap_external>\", line 1131, in _get_spec\r\n  File \"<frozen importlib._bootstrap_external>\", line 1112, in _legacy_get_spec\r\n  File \"<frozen importlib._bootstrap>\", line 441, in spec_from_loader\r\n  File \"<frozen importlib._bootstrap_external>\", line 544, in spec_from_file_location\r\n  File \"/tmp/ansible_ping_payload_o4qr2fux/ansible_ping_payload.zip/ansible/module_utils/basic.py\", line 5\r\nSyntaxError: future feature annotations is not defined\r\n",
-    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
-    "rc": 1
-}
-hsuma@plnx-admin:~/haj/ansible-setup-hosts$ 
-
-
-hsuma@plnx-admin:~/haj/ansible-setup-hosts$ ansible all -i inventory -m ping -u deploy -b
-/usr/lib/python3/dist-packages/paramiko/pkey.py:82: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
-  "cipher": algorithms.TripleDES,
-/usr/lib/python3/dist-packages/paramiko/transport.py:237: CryptographyDeprecationWarning: Blowfish has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.Blowfish and will be removed from this module in 45.0.0.
-  "class": algorithms.Blowfish,
-/usr/lib/python3/dist-packages/paramiko/transport.py:261: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
-  "class": algorithms.TripleDES,
-[WARNING]: Platform linux on host 10.168.0.58 is using the discovered Python interpreter at /usr/bin/python3.11, but future installation of another
-Python interpreter could change the meaning of that path. See https://docs.ansible.com/ansible-
-core/2.17/reference_appendices/interpreter_discovery.html for more information.
-10.168.0.58 | SUCCESS => {
-    "ansible_facts": {
-        "discovered_interpreter_python": "/usr/bin/python3.11"
-    },
-    "changed": false,
-    "ping": "pong"
-}
-hsuma@plnx-admin:~/haj/ansible-setup-hosts$ 
-
-
-cat <<EOF > ~/haj/ansible-setup-hosts/ansible.cfg
-[defaults]
-interpreter_python = /usr/bin/python3.11
-deprecation_warnings = False
-command_warnings = False
-stdout_callback = yaml
-EOF
-
-
-hsuma@plnx-admin:~/haj/ansible-setup-hosts$ ansible all -i inventory -m ping -u deploy -b
-10.168.0.58 | SUCCESS => {
-    "changed": false,
-    "ping": "pong"
-}
-hsuma@plnx-admin:~/haj/ansible-setup-hosts$ ansible-playbook mine -i inventory -u deploy -b
-
-PLAY [VM Configuration Update and DNS Setup] **********************************************************************************************************
-
-TASK [Gathering Facts] ********************************************************************************************************************************
-ok: [10.168.0.58]
-
-TASK [Update ipa_server entry in /etc/sssd/sssd.conf] *************************************************************************************************
-changed: [10.168.0.58]
-
-PLAY RECAP ********************************************************************************************************************************************
-10.168.0.58                : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
-
-hsuma@plnx-admin:~/haj/ansible-setup-hosts$ cat mine 
----
-- name: VM Configuration Update and DNS Setup
-  hosts: all
-  become: yes
-  tasks:
-
-  - name: Update ipa_server entry in /etc/sssd/sssd.conf
-    lineinfile:
-      path: /etc/sssd/sssd.conf
-      regexp: '^ipa_server ='
-      line: 'ipa_server = _srv_, pln-petipareplica.ipa.calix.local, cpeg-ipareplica.ipa.calix.local'
-      state: present
-      backrefs: no
-
-# Uncomment the following task if a system reboot is required after configuration updates
-#  - name: Reboot the system
-#    reboot:
-#      msg: "Rebooting to apply changes"
-#      pre_reboot_delay: 10
-
-hsuma@plnx-admin:~/haj/ansible-setup-hosts$ 
-
----
-- name: VM Configuration Update and DNS Setup
-  hosts: all
-  become: yes
-  tasks:
-
-  - name: Update ipa_server entry in /etc/sssd/sssd.conf
-    lineinfile:
-      path: /etc/sssd/sssd.conf
-      regexp: '^ipa_server ='
-      line: 'ipa_server = _srv_, pln-petipareplica.ipa.calix.local, cpeg-ipareplica.ipa.calix.local'
-      state: present
-      backrefs: no
-    notify: Restart SSSD
-
-  handlers:
-    - name: Restart SSSD
-      service:
-        name: sssd
-        state: 
-
-
-
-hsuma@plnx-admin:~/haj/ansible-setup-hosts$ ansible-playbook mine -i inventory -u deploy -b
-
-PLAY [VM Configuration Update and DNS Setup] **********************************************************************************************************
-
-TASK [Gathering Facts] ********************************************************************************************************************************
-ok: [10.168.0.58]
-
-TASK [Update ipa_server entry in /etc/sssd/sssd.conf] *************************************************************************************************
-changed: [10.168.0.58]
-
-RUNNING HANDLER [Restart SSSD] ************************************************************************************************************************
-fatal: [10.168.0.58]: FAILED! => changed=false 
-  msg: 'value of state must be one of: reloaded, restarted, started, stopped, got: None'
-
-PLAY RECAP ********************************************************************************************************************************************
-10.168.0.58                : ok=2    changed=1    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
-
-hsuma@plnx-admin:~/haj/ansible-setup-hosts$ vi mine 
-hsuma@plnx-admin:~/haj/ansible-setup-hosts$ ansible-playbook mine -i inventory -u deploy -b
-
-PLAY [VM Configuration Update and DNS Setup] **********************************************************************************************************
-
-TASK [Gathering Facts] ********************************************************************************************************************************
-ok: [10.168.0.58]
-
-TASK [Update ipa_server entry in /etc/sssd/sssd.conf] *************************************************************************************************
-ok: [10.168.0.58]
-
-PLAY RECAP ********************************************************************************************************************************************
-10.168.0.58                : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
-
-hsuma@plnx-admin:~/haj/ansible-setup-hosts$ 
-
-
-
----
-- name: VM Configuration Update and DNS Setup
-  hosts: all
-  become: yes
-  tasks:
-
-  - name: Update ipa_server entry in /etc/sssd/sssd.conf
-    lineinfile:
-      path: /etc/sssd/sssd.conf
-      regexp: '^ipa_server ='
-      line: 'ipa_server = _srv_, pln-petipareplica.ipa.calix.local, cpeg-ipareplica.ipa.calix.local'
-      state: present
-      backrefs: no
-    notify: Restart SSSD
-
-  - name: Ensure SSSD is restarted if no changes were detected
-    command: systemctl restart sssd
-    become: yes
-    changed_when: false  # Avoid marking as changed in playbook summary
-    when: ansible_run_tags is not defined or "always_restart_sssd" in ansible_run_tags
-
-  handlers:
-  - name: Restart SSSD
-    service:
-      name: sssd
-
-
-hsuma@plnx-admin:~/haj/ansible-setup-hosts$ ansible-playbook mine -i inventory -u deploy -b
-
-PLAY [VM Configuration Update and DNS Setup] **********************************************************************************************************
-
-TASK [Gathering Facts] ********************************************************************************************************************************
-ok: [10.168.0.58]
-
-TASK [Update ipa_server entry in /etc/sssd/sssd.conf] *************************************************************************************************
-ok: [10.168.0.58]
-
-TASK [Ensure SSSD is restarted if no changes were detected] *******************************************************************************************
-skipping: [10.168.0.58]
-
-PLAY RECAP ********************************************************************************************************************************************
-10.168.0.58                : ok=2    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
-
-hsuma@plnx-admin:~/haj/ansible-setup-hosts$ 
-      
----
-- name: VM Configuration Update and DNS Setup
-  hosts: all
-  become: yes
-  tasks:
-
-  - name: Update ipa_server entry in /etc/sssd/sssd.conf
-    lineinfile:
-      path: /etc/sssd/sssd.conf
-      regexp: '^ipa_server ='
-      line: 'ipa_server = _srv_, pln-petipareplica.ipa.calix.local, cpeg-ipareplica.ipa.calix.local'
-      state: present
-      backrefs: no
-    notify: Restart SSSD
-
-  - name: Ensure SSSD is restarted
-    service:
-      name: sssd
-      state: restarted
-    become: yes
-
-  handlers:
-  - name: Restart SSSD
-    service:
-      name: sssd
-      state: restarted
-
+echo "SSSD configuration update complete."
+exit 0
